### ISSUE TITLE
delete Entry

### ISSUE THREAD

**Issue by cptechnik** [ramack/ActivityDiary#258] opened 2019-01-14 06:49 UTC
... maybe I'm old but I can't delete an entry...
How?

**Comment by ramack** [comment] 2019-01-14 19:31
thanks for the feedback, @cptechnik I can confirm, that this is not related to your age. The feature to delete is actually just not yet implemented, as documented in #28 - shame on me, that it takes so long and it is already labeled with "high prio". But you are totally right bothering me, this is a good way to define priorities!

closing, since duplicate (#28).

Workaround: to delete an entry you can "simply" export the data, modify it on your computer (e.g. by sqlite browser) and re-import it. (It will work, but yes, I don't mean this to be a serious option :grin:)

**Closed by ramack** 2019-01-14 19:31 UTC
Labels: duplicate

**Comment by cptechnik** [comment] 2019-01-20 12:12
Thank you for this comment and refer to #28!

**Comment by alm10965** [comment] 2019-05-26 15:18
Sorry wtf, how can I test a new app, and I can't delete entries!?
