### ISSUE TITLE
Pictures added to diary activity not showing

### ISSUE THREAD

**Issue by mcyusuf** [ramack/ActivityDiary#80] opened 2018-02-12 16:15 UTC
#### Expected behavior
I was expecting to see previews or thumbnails of the pics in the respective activity I added a pics to. 

#### Actual behavior
I couldn't see any pics or thumbnails, all I got was a plain white background in place of the pics.

#### How to reproduce
Download activity diary on fdroid (latest version is 1.1.1).
Select an activity such as gardening.
Click the camera icon to add a pics to the activity.
Now check the activity on the main page, you'd see white background rather than pictures.
Also check the diary submenu, still the same view under the activity.

* App: Activitydiary app for Android
* Operating system: 
>Android Lollipop 5.1 tablet & Nougat 7.0 tecno k7.

#### Recording Of The Bug
![videotogif_2018.02.08_19.36.37.gif](https://steemitimages.com/DQmVb8UKLMo3HDQG8jGMpofVj6QeQ3D2YkbmVe4z3Ju2S9c/videotogif_2018.02.08_19.36.37.gif)
![videotogif_2018.02.08_19.40.20.gif](https://steemitimages.com/DQmYNXBXqnNmsaFB7WW4rEuVWd1jo4HmPFa8QnAWPyNdAQ7/videotogif_2018.02.08_19.40.20.gif)
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@mcyusuf/pictures-added-to-diary-activity-not-showing">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ramack** [comment] 2018-02-12 16:44
Wow. Great bug report. Thanks a lot.

I cannot reproduce it on my devices and have currently no idea where it could cone from. So I'd like to ask whether you could take a look at the Pictures directory on your device. Do the images show up there? How did you configure the storage folder for pictures in ActivityDiary?

**Comment by mcyusuf** [comment] 2018-02-12 16:50
I can find the pictures taken on my storage. 
I used it default folder. It saves in pictures/activitydiary

**Comment by ramack** [comment] 2018-02-12 19:55
Can you check whether the activity name is in the Exit metadata in the pictures?

**Comment by mcyusuf** [comment] 2018-02-12 20:34
Not sure how to get the metadata. But the file name has the activity in it. 
Here is one of the pics name as stored.:
IMG_Swimming_20180211_183438177538306.jpg

**Comment by ramack** [comment] 2018-02-13 06:58
Ok thx. I will look into the code this weekend.

**Comment by mcyusuf** [comment] 2018-02-13 08:49
Okay. That wouod be nice. Would await the new update.

**Comment by ramack** [comment] 2018-02-16 23:17
tentitive fix checked in. But still I cannot reproduce the issue, so answers to the above questions still would help.

**Comment by mcyusuf** [comment] 2018-02-17 07:14
It happens the same on both my phone's. A tablet running lollipop 5.1 and tecno k7 running 7.0 nougat.

Making use of the phone's software camera. That is the one that came with the OS. It picks up the activity once I click the camera icon.

**Comment by mcyusuf** [comment] 2018-02-17 09:14
![img_gardening_20180217_081657984986702](https://user-images.githubusercontent.com/35164646/36339655-ef642cb2-13ca-11e8-92b8-d8689b2b94f3.jpg)

That's one of the pics taken today from the app
And a screenshot of it here
![screenshot_20180217-081731](https://user-images.githubusercontent.com/35164646/36339684-58c90038-13cb-11e8-8107-a2cd546ef29f.png)

**Comment by ramack** [comment] 2018-02-17 09:15
Oh, that means it also works sometimes? Do you see a difference? Maybe the orientation?

**Comment by mcyusuf** [comment] 2018-02-17 09:17
You mean I should change my device orientation

**Comment by mcyusuf** [comment] 2018-02-17 09:19
Still same results. 
![screenshot_20180217-101835](https://user-images.githubusercontent.com/35164646/36339716-ffd13c6a-13cb-11e8-9f8a-873c8ca99f7e.png)

**Comment by mcyusuf** [comment] 2018-02-17 09:20
Since it works on your device. Kindly show me a screengrab. So I can see the difference

**Comment by ramack** [comment] 2018-02-17 11:51
Ah, no. I meant the picture to be landscape or portrait...
A screenshot from me is here https://github.com/ramack/ActivityDiary/blob/master/app/src/main/play/de-DE/listing/phoneScreenshots/01_Screenshot_SelectActivity.png

**Comment by ramack** [comment] 2018-02-17 11:54
The picture and the screenshot you have provided above shows a picture in portrait, while the (empty) picture frame in activitydiary seems landscape...

**Comment by mcyusuf** [comment] 2018-02-17 13:36
Tested
![videotogif_2018 02 17_13 01 46](https://user-images.githubusercontent.com/35164646/36340888-f8caeab4-13e5-11e8-85f7-ca89e6d618cc.gif)

**Comment by ramack** [comment] 2018-02-17 20:18
Thanks for the video. Do you know how to read the logcat? - It would be interesting to see what is in there during the phase of taking a picture and showing the empty box...

And - sorry for asking again - does it work on your device sometimes or never?

**Comment by ramack** [comment] 2018-02-17 20:34
It may sound crude, but you clicked "ALLOW" on requesting access for the storage, right?

**Comment by ramack** [comment] 2018-02-18 10:28
Do you use Google Play? - I pushed yesterday a new version (1.1.7-beta) to the beta track in PlayStore. - Would be great, if you could give it a try.

**Comment by mcyusuf** [comment] 2018-02-18 16:50
* I am not a techy. Can't read logcat. 
* Since I had it installed, never got pics shown in it at all.
* Yes. Clicked allow. That's how nougat asks for access at first for permissions. 
* I use Google Play, would check out the beta. 
Thanks...

**Comment by mcyusuf** [comment] 2018-02-19 12:24
I can't get to see beta apps on my playstore. Kindly help me share the file as zip here. Thanks.

**Comment by ramack** [comment] 2018-02-20 20:59
Can you check:
- The settings of "Crash Reporting" and "Metadata"?
- Can you export your data using "Settings/Export Database" and send the file to my by email (activity-diary@rampro.de) - but please only if you do not have personal data that is worth to protect in there!

For registering on the beta track on Google Play you can go to https://play.google.com/apps/testing/de.rampro.activitydiary and press "Become a tester". Afterwards PlayStore will update to the beta version.

**Comment by ramack** [comment] 2018-02-20 22:01
Do you have an external storage (aka SD card)?

**Comment by ramack** [comment] 2018-02-22 18:59
oops, that was accidentally closed, I'd say

**Comment by ramack** [comment] 2018-05-05 21:46
This is hard to track down without seeing (and debugging) the issue. Let's see whether it is/was a picasso issue.
The other idea would be a privilege topic for with the FileProvider, but this would need a logcat. @mcyusuf  or @celizstine do you see a chance to send some logs? Otherwise I have to shift it yet again to the next release.

**Comment by mcyusuf** [comment] 2018-05-06 01:39
Would get back to you with a logcat for my lollipop device tomorrow. My PC is down, so I can extract logcat without root.
Thanks

**Comment by ramack** [comment] 2018-05-07 19:37
would be great to understand more details. Thanks for all your efforts.

**Comment by mcyusuf** [comment] 2018-05-07 19:58
Using the latest beta version. 
While fondling with taking pics just now. Noticed the pics I had above 2mb didn't get loaded. But those with a lower size was displayed.

**Comment by mcyusuf** [comment] 2018-05-07 20:07
Maybe it had something to do with the picture size. Using a 12mp rear camera. And with Max quality, I get pics of about 5mb.

**Comment by mcyusuf** [comment] 2018-05-07 20:43
Okies. Let me know when it's release, would be glad to have a look at the issue again. Thanks for the efforts.

**Comment by ramack** [comment] 2018-05-10 17:33
I shift this to the next release to have a clean state for 1.2.0. If that release fixes the issue really, please close it.

**Comment by ramack** [comment] 2018-05-20 09:04
could you already try with v1.2.2?

**Comment by mcyusuf** [comment] 2018-05-20 19:52
I would get to update tomorrow and check it out

**Closed** 2018-07-07 18:45 UTC
Labels: bug
