### ISSUE TITLE
Can't take photo

### ISSUE THREAD

**Issue by sjl872964789** [ramack/ActivityDiary#308] opened 2022-03-15 07:56 UTC
**Describe the bug**
I found that I couldn't use ActivityDiary properly because I couldn't use the camera function, to make sure I didn't change any weird settings I cleared the ActivityDiary and restarted it, but it didn't seem to work

**To Reproduce**
1. Open the app
2. Click on any tab
3. Click the photo button

**Expected behavior**
pop-up photo interface

**Screenshots**
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/15941953/158331468-a3398e67-9618-436e-b830-35bee214c2b9.gif)

**Smartphone (please complete the following information):**
 - OS: Hydrogen OS
 - Rooted: No
 - Version: 1.4.2
 - Device: OnePlus 8T

**Comment by ramack** [comment] 2022-03-15 08:00
Thanks for the report. Can you try to explicitly grant camera access in the systems (not in the settings within ActivityDiary) app settings?

**Comment by sjl872964789** [comment] 2022-03-15 08:06
Strangely, on my device ActivityDiary doesn't requestcamera permission, and I don't know how to grant it, as follow
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/15941953/158333172-7f3a7b37-56e8-4466-8dc0-0a9d991110ce.gif)

**Comment by ramack** [comment] 2022-04-18 19:59
I cannot reproduce that, so for now I think it is related to Hydrogen OS and propose to close it, as I cannot debug it. In case you have AndroidStudio and want to step though it and see what is wrong, I'd be happy to merge a pull request!

**Closed by ramack** 2022-04-18 19:59 UTC
