### ISSUE TITLE
image not showing when snap is added

### ISSUE THREAD

**Issue by celizstine** [ramack/ActivityDiary#108] opened 2018-02-28 16:33 UTC
#### Expected behavior
to see the snapped picture i took with the app after creating an activity with the app.

#### Actual behavior
After taking the picture with my camera, i couldnt see the image and it was just blank there.

#### How to reproduce
-download the app
launch the app
-select a tag and fill
-click the add photo
-take a snap and confirm

* Browser: infinix note 4 pro
* Operating system: android 7.0

#### Recording Of The Bug
https://youtu.be/wAHR5pdivUM
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@celizstine/image-not-showing-when-snap-is-added">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ramack** [comment] 2018-02-28 17:23
Thanks for the report. It seems to be a duplicate of #80 nevertheless some more data would be good to understand the issue in more depth.

Do you have an SDcard? 

Can you check where the picture is stored an share the absolute path here?

Which version of ActivityDiary did you use?

**Comment by ramack** [comment] 2018-03-23 23:09
As you don't give any feedback I will close that one here.

**Closed by ramack** 2018-03-23 23:09 UTC
Labels: bug, duplicate
